import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import "@cloudscape-design/global-styles/index.css";
import App from "./App";
import { AuthProvider } from "./auth/AuthContext";
import { FlashbarProvider } from "./context/FlashbarContext";
import { ImpersonationBanner } from "./components/ImpersonationBanner";
ReactDOM.createRoot(document.getElementById("root")).render(_jsx(React.StrictMode, { children: _jsx(BrowserRouter, { children: _jsx(FlashbarProvider, { children: _jsxs(AuthProvider, { children: [_jsx(ImpersonationBanner, {}), _jsx(App, {})] }) }) }) }));
